version: '3.8'

services:
  db_mysql:
    container_name: mysqlserver
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - db_network
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coba
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    container_name: adminerserver
    image: adminer:latest
    networks:
      - db_network
    ports:
      - 8081:8080

networks:
  db_network:
    driver: bridge